// <auto-generated />
using System;
using KetNoiDatabaseNhieuBang.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KetNoiDatabaseNhieuBang.Migrations
{
    [DbContext(typeof(Net1021012Context))]
    [Migration("20250731030917_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KetNoiDatabaseNhieuBang.Models.DocGium", b =>
                {
                    b.Property<int>("MaDocGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDocGia"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDocGia")
                        .HasName("PK__DocGia__F165F945A8BFAC16");

                    b.HasIndex(new[] { "Email" }, "UQ__DocGia__A9D10534180C0CF0")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("DocGia");
                });

            modelBuilder.Entity("KetNoiDatabaseNhieuBang.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"));

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ISBN");

                    b.Property<int?>("MaTacGia")
                        .HasColumnType("int");

                    b.Property<int?>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongTonKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaSach")
                        .HasName("PK__Sach__B235742D1542F904");

                    b.HasIndex("MaTacGia");

                    b.HasIndex(new[] { "Isbn" }, "UQ__Sach__447D36EAA801EA8A")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Sach", (string)null);
                });

            modelBuilder.Entity("KetNoiDatabaseNhieuBang.Models.TacGium", b =>
                {
                    b.Property<int>("MaTacGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTacGia"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTacGia")
                        .HasName("PK__TacGia__F24E67562AE9DC79");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("KetNoiDatabaseNhieuBang.Models.Sach", b =>
                {
                    b.HasOne("KetNoiDatabaseNhieuBang.Models.TacGium", "MaTacGiaNavigation")
                        .WithMany("Saches")
                        .HasForeignKey("MaTacGia")
                        .HasConstraintName("FK__Sach__MaTacGia__286302EC");

                    b.Navigation("MaTacGiaNavigation");
                });

            modelBuilder.Entity("KetNoiDatabaseNhieuBang.Models.TacGium", b =>
                {
                    b.Navigation("Saches");
                });
#pragma warning restore 612, 618
        }
    }
}
